FROM ghcr.io/netbootxyz/docker-builder:latest as builder

# repo for build
COPY . /ansible

RUN \
 echo "**** running ansible ****" && \
 cd /ansible && \
 ansible-playbook -i inventory site.yml --extra-vars "@script/netbootxyz-overrides.yml"

# runtime stage
FROM alpine:3.12

COPY --from=builder /var/www/html/ /mnt/
COPY docker-build-root/ /

ENTRYPOINT [ "/dumper.sh" ]
