FROM ghcr.io/netbootxyz/builder:latest as builder

# repo for build
COPY . /ansible

RUN \
 echo "**** running ansible ****" && \
 cd /ansible && \
 ansible-playbook -i inventory site.yml

# runtime stage
FROM alpine:latest

COPY --from=builder /var/www/html/ /mnt/
COPY docker-build-root/ /

ENTRYPOINT [ "/dumper.sh" ]
