#!/bin/bash

TYPE=$1

# Set boot domain
if [[ "${TYPE}" == "dev" ]]; then
  BOOT_DOMAIN="s3.amazonaws.com/${BUCKET_DEV}/${TRAVIS_COMMIT}"
elif [[ "${TYPE}" == "pr" ]]; then
  BOOT_DOMAIN="test.com"
elif [[ "${TYPE}" == "rc" ]]; then
  BOOT_DOMAIN="staging.boot.netboot.xyz/${TRAVIS_TAG}"
elif [[ "${TYPE}" == "release" ]]; then
  BOOT_DOMAIN="staging.boot.netboot.xyz/$(cat version.txt)"
fi
sed -i \
  "/^#boot_domain/c\boot_domain: ${BOOT_DOMAIN}" \
  user_overrides.yml

# Build release
docker build -t localbuild -f Dockerfile-build .
docker run --rm -it -v $(pwd):/buildout localbuild

# Generate folder outputs
mkdir -p s3out
cp -r buildout/* s3out/
cp script/index.html s3out/
mkdir -p githubout
mv buildout/ipxe/* githubout/
cd buildout
rm -Rf ipxe
tar -czf menus.tar.gz *
mv menus.tar.gz ../githubout
cd ..


# Latest style endpoints for RC and Live
if [[ "${TYPE}" == "release" ]] || [[ "${TYPE}" == "rc" ]]; then
  rm -Rf buildout/
  if [[ "${TYPE}" == "release" ]]; then
    sed -i \
      "/^boot_domain/c\boot_domain: staging.boot.netboot.xyz" \
      user_overrides.yml
    docker build -t localbuild -f Dockerfile-build .
    docker run --rm -it -v $(pwd):/buildout localbuild
  fi
  if [[ "${TYPE}" == "rc" ]]; then
    sed -i \
      "/^boot_domain/c\boot_domain: staging.boot.netboot.xyz/rc" \
      user_overrides.yml
    docker build -t localbuild -f Dockerfile-build .
    docker run --rm -it -v $(pwd):/buildout localbuild
  fi
  mkdir -p s3out-latest
  cp -r buildout/* s3out-latest/
  cp script/index.html s3out-latest/
fi
